import type { AppState, TraceEntry } from "./types";
import { daysAgoIso, inDaysIso } from "./util";

const tr = (days: number, hour: number, user: string, msg: string): TraceEntry => ({
  ts: daysAgoIso(days, hour), user, msg,
});

export const seedState = (): AppState => ({
  hydrated: true,
  products: [
    { id: "p1", sku: "SAL-001", name: "Sofá Nápoles 3 puestos", category: "Sala", line: "fabricacion", materials: ["Madera de laurel", "Lino crudo", "Espuma D30"], cost: 480, price: 899, stock: { showroom: 3, bodega: 5, taller: 0 }, min: 3, status: "activo", img: "https://image.qwenlm.ai/generated-images/876c81bb-04b7-4ecf-b3c5-5409001f7961/_result.png", mediaIds: ["m1"], dims: "220×92×86 cm", weightKg: 68, leadDays: 21, createdAt: daysAgoIso(220) },
    { id: "p2", sku: "COM-014", name: "Comedor Andino 6 sillas", category: "Comedor", line: "fabricacion", materials: ["Roble nacional", "Acabado natural", "Sillas tapizadas"], cost: 620, price: 1189, stock: { showroom: 2, bodega: 3, taller: 2 }, min: 2, status: "activo", img: "https://image.qwenlm.ai/generated-images/c4c2d864-549d-421e-a9e9-ee3f14fc7e78/_result.png", mediaIds: ["m2"], dims: "180×100×76 cm", weightKg: 84, leadDays: 25, createdAt: daysAgoIso(190) },
    { id: "p3", sku: "DOR-030", name: "Cama King Roble Nórdica", category: "Dormitorio", line: "compra_local", materials: ["Roble", "Ensamble invisible"], cost: 350, price: 699, stock: { showroom: 1, bodega: 6, taller: 0 }, min: 2, status: "activo", img: "https://image.qwenlm.ai/generated-images/4c03f0dd-cf51-487c-964a-67a34323efb3/_result.png", mediaIds: ["m3"], dims: "210×190×105 cm", weightKg: 72, leadDays: 12, createdAt: daysAgoIso(160) },
    { id: "p4", sku: "DOR-042", name: "Ropero Amazonia 6 puertas", category: "Dormitorio", line: "fabricacion", materials: ["Laurel", "Triplex 18mm", "Bisagras slow-close"], cost: 410, price: 789, stock: { showroom: 2, bodega: 2, taller: 1 }, min: 2, status: "activo", img: "https://image.qwenlm.ai/generated-images/9248a4c4-1d9b-4611-b940-870a805ce7d5/_result.png", mediaIds: ["m4"], dims: "240×60×210 cm", weightKg: 110, leadDays: 28, createdAt: daysAgoIso(140) },
    { id: "p5", sku: "OFI-007", name: "Escritorio Ejecutivo Cañar", category: "Oficina", line: "compra_local", materials: ["Nogal", "Pasacables", "Cajonera doble"], cost: 240, price: 459, stock: { showroom: 4, bodega: 7, taller: 0 }, min: 3, status: "activo", img: "https://image.qwenlm.ai/generated-images/2c56f5e9-08cb-49de-b7a4-963536e14050/_result.png", mediaIds: ["m5"], dims: "160×75×76 cm", weightKg: 54, leadDays: 10, createdAt: daysAgoIso(120) },
    { id: "p6", sku: "SAL-023", name: "Poltrona Esmeraldas", category: "Sala", line: "importado", materials: ["Bouclé", "Base giratoria metal"], cost: 190, price: 389, stock: { showroom: 6, bodega: 4, taller: 0 }, min: 3, status: "activo", img: "https://image.qwenlm.ai/generated-images/087283f8-cf51-449d-9d01-520b4731854c/_result.png", mediaIds: ["m6"], dims: "88×90×102 cm", weightKg: 26, leadDays: 35, createdAt: daysAgoIso(100) },
    { id: "p7", sku: "COM-015", name: "Silla Comedor Andina (und)", category: "Comedor", line: "fabricacion", materials: ["Roble", "Asiento tapizado"], cost: 48, price: 99, stock: { showroom: 14, bodega: 20, taller: 8 }, min: 12, status: "activo", img: "", mediaIds: [], dims: "46×54×92 cm", weightKg: 7, leadDays: 18, createdAt: daysAgoIso(95) },
    { id: "p8", sku: "DOR-051", name: "Base + Colchón Queen Ortopédico", category: "Dormitorio", line: "compra_local", materials: ["Resortes pocket", "Tela bambú"], cost: 290, price: 559, stock: { showroom: 2, bodega: 9, taller: 0 }, min: 3, status: "activo", img: "", mediaIds: [], dims: "190×160×58 cm", weightKg: 48, leadDays: 8, createdAt: daysAgoIso(60) },
  ],
  customers: [
    { id: "c1", code: "CL-0101", name: "María Fernanda Icaza", doc: "1718456723", type: "natural", phone: "099 452 1187", email: "mficaza@gmail.com", city: "Quito", segment: "hogar", orders: 4, total: 4830, credit: 0, since: daysAgoIso(400), notes: "Prefiere entrega en fin de semana, sector Cumbayá." },
    { id: "c2", code: "CL-0114", name: "Corporación Quiport Offices", doc: "1792114587001", type: "juridica", phone: "02 395 4400", email: "compras@quiport-offices.ec", city: "Quito", segment: "corporativo", orders: 9, total: 28410, credit: 6320, since: daysAgoIso(700), notes: "Crédito a 45 días. Facturación electrónica a 3 sucursales." },
    { id: "c3", code: "CL-0127", name: "Distribuidora Mueblisur", doc: "0991234567001", type: "juridica", phone: "04 259 8810", email: "pedidos@mueblisur.ec", city: "Guayaquil", segment: "distribuidor", orders: 14, total: 51220, credit: 8900, since: daysAgoIso(900), notes: "Pedido mayorista mensual. Transporte lo coordinan ellos." },
    { id: "c4", code: "CL-0132", name: "Estudio Arq. Barragán", doc: "0104567890", type: "natural", phone: "098 771 2245", email: "proyectos@barragan.arq.ec", city: "Cuenca", segment: "arquitectura", orders: 6, total: 19750, credit: 0, since: daysAgoIso(500), notes: "Proyectos llave en mano, pide renders antes de fabricar." },
    { id: "c5", code: "CL-0140", name: "Javier Andrade Vallejo", doc: "1803345671", type: "natural", phone: "096 220 8734", email: "jandradev@hotmail.com", city: "Ambato", segment: "hogar", orders: 2, total: 1558, credit: 0, since: daysAgoIso(200), notes: "Segunda compra: mudanza a casa nueva en marzo." },
    { id: "c6", code: "CL-0155", name: "Hotel Plaza Grande Suites", doc: "1790023345001", type: "juridica", phone: "02 295 7000", email: "ffurnish@plazagrande.ec", city: "Quito", segment: "corporativo", orders: 3, total: 42300, credit: 12450, since: daysAgoIso(320), notes: "Renovación de 40 suites. Comité de compras aprueba el 15 de cada mes." },
  ],
  suppliers: [
    { id: "s1", name: "Maderera del Austro", kind: "insumos", contact: "Fausto Ordóñez", phone: "07 284 5511", email: "ventas@madereraustro.ec", city: "Cuenca", rating: 4.7, leadDays: 6, balance: 2350, items: "Laurel, roble, nogal en tabla", active: true },
    { id: "s2", name: "Espumas del Pacífico", kind: "insumos", contact: "Karla Merchán", phone: "04 248 9902", email: "kmerchan@espumaspacifico.ec", city: "Guayaquil", rating: 4.2, leadDays: 4, balance: 0, items: "Espuma D26/D30, guata, cincha", active: true },
    { id: "s3", name: "Tapices & Textiles Imbabura", kind: "insumos", contact: "Rosa Andrade", phone: "06 295 1123", email: "pedidos@tapicesimbabura.ec", city: "Ibarra", rating: 4.5, leadDays: 5, balance: 640, items: "Lino, bouclé, chenille", active: true },
    { id: "s4", name: "Importadora Mobilia Asia", kind: "muebles", contact: "Wei Chen", phone: "04 370 2218", email: "sales@mobiliaasia.ec", city: "Guayaquil", rating: 3.9, leadDays: 45, balance: 8120, items: "Poltronas y mesas importadas", active: true },
    { id: "s5", name: "TransLog Ecuador", kind: "transporte", contact: "Paúl Vega", phone: "02 382 4470", email: "ops@translog.ec", city: "Quito", rating: 4.8, leadDays: 2, balance: 380, items: "Fletes Sierra y Oriente, camión cerrado", active: true },
    { id: "s6", name: "Fletes Rápidos GYE", kind: "transporte", contact: "Mónica Saltos", phone: "04 256 7789", email: "despachos@fletesgye.ec", city: "Guayaquil", rating: 4.1, leadDays: 3, balance: 0, items: "Costa, camión 3.5t con ayudante", active: true },
  ],
  orders: [
    {
      id: "o1", code: "PED-1041", kind: "venta", customerId: "c1", customer: "María Fernanda Icaza",
      items: [{ productId: "p1", sku: "SAL-001", name: "Sofá Nápoles 3 puestos", qty: 1, price: 899, spec: null }],
      subtotal: 899, iva: 134.85, total: 1033.85, status: "despachado", channel: "tienda", payment: "pagado",
      transportId: "s5", bultos: 2, createdAt: daysAgoIso(4, 11), eta: inDaysIso(1), city: "Quito", workOrderId: null,
      trace: [tr(4, 11, "Paola C.", "Venta de stock creada · canal tienda"), tr(4, 12, "sistema", "Link PayPhone pagado · $1.033,85 · Visa •••• 4421"), tr(1, 9, "Luis Ch.", "Despacho DSP-3021 creado · TransLog · placa PCH-1194")],
      recibos: [{ id: "r1", code: "REC-0401", date: daysAgoIso(4, 12), amount: 1033.85, method: "PayPhone · Visa •••• 4421", note: "Pago total vía link", validado: true }],
      confirmToken: null, confirmedAt: null,
    },
    {
      id: "o2", code: "PED-1042", kind: "venta", customerId: "c2", customer: "Corporación Quiport Offices",
      items: [
        { productId: "p5", sku: "OFI-007", name: "Escritorio Ejecutivo Cañar", qty: 6, price: 449, spec: null },
        { productId: "p6", sku: "SAL-023", name: "Poltrona Esmeraldas", qty: 4, price: 389, spec: null },
      ],
      subtotal: 4250, iva: 637.5, total: 4887.5, status: "aprobado", channel: "link_pago", payment: "pendiente",
      transportId: null, bultos: 10, createdAt: daysAgoIso(3, 15), eta: inDaysIso(6), city: "Quito", workOrderId: null,
      trace: [tr(3, 15, "Paola C.", "Venta de stock creada · canal link de pago"), tr(3, 16, "sistema", "Link de cobro generado · anticipo 50%"), tr(2, 10, "Andrés Y.", "Pedido aprobado · crédito corporativo 45d")],
      recibos: [],
      confirmToken: null, confirmedAt: null,
    },
    {
      id: "o3", code: "PED-1043", kind: "pedido", customerId: "c4", customer: "Estudio Arq. Barragán",
      items: [{
        productId: "p2", sku: "COM-014", name: "Comedor Andino 6 sillas", qty: 2, price: 1189,
        spec: {
          tapiz: "Lino crudo T-04", tapizSec: "Chenille gris piedra", cojines: "2 por silla, mismo lino",
          lacado: "Natural mate (poro abierto)", notas: "Mesa extendida a 220 cm · esquinas rectas",
          fotos: [{ campo: "Tapiz principal", label: "lino-crudo-T04.jpg" }, { campo: "Lacado", label: "muestra-mate-poro.jpg" }],
        },
      }],
      subtotal: 2378, iva: 356.7, total: 2734.7, status: "en_produccion", channel: "web", payment: "parcial",
      transportId: null, bultos: 10, createdAt: daysAgoIso(6, 9), eta: inDaysIso(9), city: "Cuenca", workOrderId: "w1",
      trace: [
        tr(6, 9, "Paola C.", "Pedido bajo specs creado · canal web"),
        tr(6, 10, "sistema", "Link único de confirmación (con fotos) enviado al cliente"),
        tr(5, 17, "cliente", "Cliente confirmó specs y fotos del link único"),
        tr(5, 9, "Rocío M.", "Recibo REC-0402 · anticipo 50% por transferencia — validado"),
        tr(4, 8, "Diego G.", "Inició producción en taller · OF-2101"),
      ],
      recibos: [{ id: "r2", code: "REC-0402", date: daysAgoIso(5, 9), amount: 1367.35, method: "Transferencia Bco. Pichincha", note: "Anticipo 50%", validado: true }],
      confirmToken: "cf_Xk29mQw7Lp", confirmedAt: daysAgoIso(5, 17),
    },
    {
      id: "o4", code: "PED-1044", kind: "venta", customerId: "c5", customer: "Javier Andrade Vallejo",
      items: [
        { productId: "p3", sku: "DOR-030", name: "Cama King Roble Nórdica", qty: 1, price: 699, spec: null },
        { productId: "p8", sku: "DOR-051", name: "Base + Colchón Queen Ortopédico", qty: 1, price: 559, spec: null },
      ],
      subtotal: 1258, iva: 188.7, total: 1446.7, status: "pendiente", channel: "whatsapp", payment: "pendiente",
      transportId: null, bultos: 4, createdAt: daysAgoIso(0, 9), eta: inDaysIso(5), city: "Ambato", workOrderId: null,
      trace: [tr(0, 9, "Paola C.", "Venta de stock creada · canal WhatsApp")],
      recibos: [],
      confirmToken: null, confirmedAt: null,
    },
    {
      id: "o5", code: "PED-1038", kind: "venta", customerId: "c6", customer: "Hotel Plaza Grande Suites",
      items: [{ productId: "p6", sku: "SAL-023", name: "Poltrona Esmeraldas", qty: 12, price: 369, spec: null }],
      subtotal: 4428, iva: 664.2, total: 5092.2, status: "entregado", channel: "link_pago", payment: "pagado",
      transportId: "s6", bultos: 12, createdAt: daysAgoIso(18, 12), eta: daysAgoIso(2), city: "Quito", workOrderId: null,
      trace: [tr(18, 12, "Paola C.", "Venta de stock creada · canal link de pago"), tr(16, 10, "sistema", "Link PayPhone pagado · $5.092,20"), tr(3, 8, "Luis Ch.", "Despacho DSP-3019 en ruta · placa GSF-2210"), tr(2, 15, "M. Saltos", "Entregado · 12 bultos conformados")],
      recibos: [{ id: "r3", code: "REC-0398", date: daysAgoIso(16, 10), amount: 5092.2, method: "PayPhone · Visa", note: "Pago total vía link", validado: true }],
      confirmToken: null, confirmedAt: null,
    },
    {
      id: "o6", code: "PED-1036", kind: "venta", customerId: "c3", customer: "Distribuidora Mueblisur",
      items: [
        { productId: "p1", sku: "SAL-001", name: "Sofá Nápoles 3 puestos", qty: 4, price: 829, spec: null },
        { productId: "p4", sku: "DOR-042", name: "Ropero Amazonia 6 puertas", qty: 2, price: 749, spec: null },
      ],
      subtotal: 4814, iva: 722.1, total: 5536.1, status: "listo_despacho", channel: "web", payment: "pendiente",
      transportId: null, bultos: 14, createdAt: daysAgoIso(8, 16), eta: inDaysIso(3), city: "Guayaquil", workOrderId: "w2",
      trace: [
        tr(8, 16, "Paola C.", "Venta de stock creada · canal web"),
        tr(2, 11, "sistema", "Recibo REC-0407 registrado · $1.500,00 — esperando validación del dueño"),
        tr(1, 10, "Luis Ch.", "Pedido listo para despacho · 14 bultos"),
      ],
      recibos: [{ id: "r4", code: "REC-0407", date: daysAgoIso(2, 11), amount: 1500, method: "Depósito Bco. Guayaquil", note: "Abono parcial · comprobante enviado por WhatsApp", validado: false }],
      confirmToken: null, confirmedAt: null,
    },
    {
      id: "o7", code: "PED-1030", kind: "venta", customerId: "c2", customer: "Corporación Quiport Offices",
      items: [{ productId: "p7", sku: "COM-015", name: "Silla Comedor Andina (und)", qty: 24, price: 92, spec: null }],
      subtotal: 2208, iva: 331.2, total: 2539.2, status: "entregado", channel: "tienda", payment: "pagado",
      transportId: "s5", bultos: 8, createdAt: daysAgoIso(25, 10), eta: daysAgoIso(9), city: "Quito", workOrderId: null,
      trace: [tr(25, 10, "Paola C.", "Venta de stock creada · canal tienda"), tr(9, 12, "P. Vega", "Entregado en oficinas Quiport")],
      recibos: [{ id: "r5", code: "REC-0390", date: daysAgoIso(24, 12), amount: 2539.2, method: "Transferencia Bco. Pichincha", note: "Pago total", validado: true }],
      confirmToken: null, confirmedAt: null,
    },
    {
      id: "o8", code: "PED-1045", kind: "pedido", customerId: "c4", customer: "Estudio Arq. Barragán",
      items: [{
        productId: "p4", sku: "DOR-042", name: "Ropero Amazonia 6 puertas", qty: 1, price: 789,
        spec: {
          tapiz: "", tapizSec: "", cojines: "", lacado: "Nogal satinado",
          notas: "Fondo espejado · iluminación LED interior",
          fotos: [{ campo: "Lacado", label: "nogal-satinado.jpg" }],
        },
      }],
      subtotal: 789, iva: 118.35, total: 907.35, status: "por_aprobar", channel: "web", payment: "pendiente",
      transportId: null, bultos: 3, createdAt: daysAgoIso(0, 8), eta: inDaysIso(12), city: "Cuenca", workOrderId: null,
      trace: [tr(0, 8, "sistema", "Pedido bajo specs recibido del cotizador web"), tr(0, 8, "sistema", "Pasó a POR APROBAR · requiere revisión de specs")],
      recibos: [],
      confirmToken: null, confirmedAt: null,
    },
  ],
  movements: [
    { id: "mv1", ts: daysAgoIso(0, 9), type: "egreso", warehouse: "showroom", productId: "p1", sku: "SAL-001", productName: "Sofá Nápoles 3 puestos", qty: 1, ref: "PED-1041", user: "Luis Ch." },
    { id: "mv2", ts: daysAgoIso(1, 15), type: "ingreso", warehouse: "bodega", productId: "p3", sku: "DOR-030", productName: "Cama King Roble Nórdica", qty: 4, ref: "OC-2208", user: "Luis Ch." },
    { id: "mv3", ts: daysAgoIso(1, 11), type: "transferencia", warehouse: "taller", productId: "p2", sku: "COM-014", productName: "Comedor Andino 6 sillas", qty: 2, ref: "OF-2101", user: "Diego G." },
    { id: "mv4", ts: daysAgoIso(2, 17), type: "ingreso", warehouse: "bodega", productId: "p6", sku: "SAL-023", productName: "Poltrona Esmeraldas", qty: 10, ref: "IMP-118", user: "Luis Ch." },
    { id: "mv5", ts: daysAgoIso(3, 10), type: "ajuste", warehouse: "showroom", productId: "p7", sku: "COM-015", productName: "Silla Comedor Andina (und)", qty: 2, ref: "AJU-31 (merma tapiz)", user: "Luis Ch." },
    { id: "mv6", ts: daysAgoIso(4, 12), type: "egreso", warehouse: "bodega", productId: "p5", sku: "OFI-007", productName: "Escritorio Ejecutivo Cañar", qty: 6, ref: "PED-1042", user: "Luis Ch." },
  ],
  workOrders: [
    { id: "w1", code: "OF-2101", productId: "p2", productName: "Comedor Andino 6 sillas", qty: 2, status: "ensamblaje", start: daysAgoIso(6), due: inDaysIso(9), assignedTo: "Diego Guamán", progress: 55, orderId: "o3", materials: [{ name: "Tabla roble 2\"", qty: "14 und", cost: 320 }, { name: "Tapiz lino crudo", qty: "9 m", cost: 96 }, { name: "Espuma D30 asiento", qty: "12 planchas", cost: 84 }], laborCost: 210 },
    { id: "w2", code: "OF-2102", productId: "p4", productName: "Ropero Amazonia 6 puertas", qty: 2, status: "acabado", start: daysAgoIso(12), due: inDaysIso(3), assignedTo: "Segundo M.", progress: 78, orderId: "o6", materials: [{ name: "Triplex 18mm", qty: "6 planchas", cost: 282 }, { name: "Canto PVC nogal", qty: "60 m", cost: 48 }, { name: "Bisagras slow-close", qty: "24 und", cost: 96 }], laborCost: 180 },
    { id: "w3", code: "OF-2103", productId: "p6", productName: "Poltrona Esmeraldas", qty: 6, status: "corte", start: daysAgoIso(1), due: inDaysIso(14), assignedTo: "Diego Guamán", progress: 22, orderId: null, materials: [{ name: "Bouclé esmeralda", qty: "16 m", cost: 176 }, { name: "Base giratoria", qty: "6 und", cost: 132 }], laborCost: 150 },
    { id: "w4", code: "OF-2104", productId: "p7", productName: "Silla Comedor Andina (und)", qty: 24, status: "qa", start: daysAgoIso(9), due: inDaysIso(2), assignedTo: "Segundo M.", progress: 90, orderId: null, materials: [{ name: "Cuadrante roble", qty: "96 m", cost: 288 }, { name: "Asiento tapizado", qty: "24 und", cost: 144 }], laborCost: 240 },
  ],
  payLinks: [
    { id: "pl1", token: "pp_9Kf3WqLm2ZxR", concept: "Anticipo 50% · PED-1042 Quiport Offices", orderId: "o2", amount: 2443.75, customerName: "Corporación Quiport Offices", createdAt: daysAgoIso(3, 16), expiresAt: inDaysIso(4), status: "pendiente", method: null, authCode: null, last4: null },
    { id: "pl2", token: "pp_T7bNcV4jH1sQ", concept: "Saldo pedido · PED-1036 Mueblisur", orderId: "o6", amount: 4036.1, customerName: "Distribuidora Mueblisur", createdAt: daysAgoIso(2, 9), expiresAt: inDaysIso(5), status: "pendiente", method: null, authCode: null, last4: null },
    { id: "pl3", token: "pp_Zx8RdM3pK6wA", concept: "Venta web · Sofá Nápoles", orderId: "o1", amount: 1033.85, customerName: "María Fernanda Icaza", createdAt: daysAgoIso(4, 12), expiresAt: daysAgoIso(2), status: "pagado", method: "PayPhone · Visa", authCode: "00442187", last4: "4421" },
    { id: "pl4", token: "pp_Q2hJvB9nS5tE", concept: "Reserva poltrona (venció)", orderId: null, amount: 389, customerName: "Cliente web sin registro", createdAt: daysAgoIso(9, 10), expiresAt: daysAgoIso(7), status: "expirado", method: null, authCode: null, last4: null },
  ],
  accessLinks: [
    { id: "al1", token: "ac_V4nWq8LmZ1xK", label: "Inventario bodega — Luis", role: "bodega", scope: "Movimientos y kardex", createdAt: daysAgoIso(5, 9), expiresAt: inDaysIso(2), maxUses: 1, uses: 1, status: "usado" },
    { id: "al2", token: "ac_H7sRd3pN6cJf", label: "Cobranzas semana — Rocío", role: "contabilidad", scope: "CxC, recibos por validar y conciliación", createdAt: daysAgoIso(1, 8), expiresAt: inDaysIso(6), maxUses: 1, uses: 0, status: "activo" },
    { id: "al3", token: "ac_B2mTv9qXw4Ls", label: "Confirmar specs comedor — Barragán", role: "cliente", scope: "Link único con fotos de spec", createdAt: daysAgoIso(6, 10), expiresAt: inDaysIso(1), maxUses: 1, uses: 1, status: "usado" },
    { id: "al4", token: "ac_Y6kPf1nGz8Rd", label: "Catálogo mayorista Mueblisur", role: "cliente", scope: "Lista de precios distribuidor", createdAt: daysAgoIso(12, 11), expiresAt: daysAgoIso(5), maxUses: 1, uses: 0, status: "expirado" },
    { id: "al5", token: "ac_J9wQm5tVb2Hn", label: "Auditoría externa (revocado)", role: "gerencia", scope: "Reportes financieros", createdAt: daysAgoIso(20, 10), expiresAt: daysAgoIso(10), maxUses: 1, uses: 0, status: "revocado" },
  ],
  media: [
    { id: "m1", name: "sofa-napoles-hero.jpg", kind: "foto", tag: "Sala", size: "2,4 MB", src: "https://image.qwenlm.ai/generated-images/876c81bb-04b7-4ecf-b3c5-5409001f7961/_result.png", usage: ["PIM · SAL-001", "Catálogo web"], uploadedAt: daysAgoIso(30) },
    { id: "m2", name: "comedor-andino-estudio.jpg", kind: "foto", tag: "Comedor", size: "2,1 MB", src: "https://image.qwenlm.ai/generated-images/c4c2d864-549d-421e-a9e9-ee3f14fc7e78/_result.png", usage: ["PIM · COM-014", "Instagram"], uploadedAt: daysAgoIso(28) },
    { id: "m3", name: "cama-king-roble.jpg", kind: "foto", tag: "Dormitorio", size: "1,9 MB", src: "https://image.qwenlm.ai/generated-images/4c03f0dd-cf51-487c-964a-67a34323efb3/_result.png", usage: ["PIM · DOR-030"], uploadedAt: daysAgoIso(25) },
    { id: "m4", name: "ropero-amazonia-amb.jpg", kind: "foto", tag: "Dormitorio", size: "2,6 MB", src: "https://image.qwenlm.ai/generated-images/9248a4c4-1d9b-4611-b940-870a805ce7d5/_result.png", usage: ["PIM · DOR-042"], uploadedAt: daysAgoIso(21) },
    { id: "m5", name: "escritorio-canar.jpg", kind: "foto", tag: "Oficina", size: "1,7 MB", src: "https://image.qwenlm.ai/generated-images/2c56f5e9-08cb-49de-b7a4-963536e14050/_result.png", usage: ["PIM · OFI-007", "Link cotización"], uploadedAt: daysAgoIso(18) },
    { id: "m6", name: "poltrona-esmeraldas.jpg", kind: "foto", tag: "Sala", size: "2,2 MB", src: "https://image.qwenlm.ai/generated-images/087283f8-cf51-449d-9d01-520b4731854c/_result.png", usage: ["PIM · SAL-023", "Catálogo web", "Meta Ads"], uploadedAt: daysAgoIso(15) },
    { id: "m7", name: "plano-comedor-andino.dwg", kind: "plano", tag: "Taller", size: "840 KB", src: "", usage: ["OF-2101", "OF-2104"], uploadedAt: daysAgoIso(12) },
    { id: "m8", name: "render-suite-hotel.png", kind: "render", tag: "Proyectos", size: "3,8 MB", src: "", usage: ["Cotización Hotel Plaza Grande"], uploadedAt: daysAgoIso(8) },
  ],
  journal: [
    { id: "j1", date: daysAgoIso(0, 9), doc: "FAC-000231", account: "1020 Bancos Pichincha", detail: "Cobro PayPhone · PED-1038", debit: 5092.2, credit: 0 },
    { id: "j2", date: daysAgoIso(0, 9), doc: "FAC-000231", account: "4010 Ventas", detail: "Venta 12 poltronas · Hotel Plaza Grande", debit: 0, credit: 4428 },
    { id: "j3", date: daysAgoIso(0, 9), doc: "FAC-000231", account: "2030 IVA por pagar", detail: "IVA 15% facturado", debit: 0, credit: 664.2 },
    { id: "j4", date: daysAgoIso(1, 11), doc: "COM-0892", account: "1040 Inventario", detail: "Compra tabla roble · Maderera del Austro", debit: 1980, credit: 0 },
    { id: "j5", date: daysAgoIso(1, 11), doc: "COM-0892", account: "1050 IVA pagado", detail: "IVA 15% en compras", debit: 297, credit: 0 },
    { id: "j6", date: daysAgoIso(1, 11), doc: "COM-0892", account: "2010 Proveedores", detail: "CxP Maderera del Austro", debit: 0, credit: 2277 },
    { id: "j7", date: daysAgoIso(2, 16), doc: "FAC-000230", account: "1030 Cuentas por cobrar", detail: "Venta crédito 45d · Quiport Offices", debit: 4887.5, credit: 0 },
    { id: "j8", date: daysAgoIso(2, 16), doc: "FAC-000230", account: "4010 Ventas", detail: "6 escritorios + 4 poltronas", debit: 0, credit: 4250 },
    { id: "j9", date: daysAgoIso(2, 16), doc: "FAC-000230", account: "2030 IVA por pagar", detail: "IVA 15% facturado", debit: 0, credit: 637.5 },
    { id: "j10", date: daysAgoIso(5, 10), doc: "GAS-0077", account: "6020 Arriendo showroom", detail: "Arriendo local Av. Eloy Alfaro", debit: 1200, credit: 0 },
    { id: "j11", date: daysAgoIso(5, 10), doc: "GAS-0077", account: "1020 Bancos Pichincha", detail: "Pago transferencia", debit: 0, credit: 1200 },
    { id: "j12", date: daysAgoIso(6, 9), doc: "ROL-0021", account: "6010 Sueldos y salarios", detail: "Nómina taller y ventas", debit: 3850, credit: 0 },
    { id: "j13", date: daysAgoIso(6, 9), doc: "ROL-0021", account: "2040 Sueldos por pagar", detail: "Pago quincena", debit: 0, credit: 3850 },
    { id: "j14", date: daysAgoIso(5, 9), doc: "REC-0402", account: "1020 Bancos Pichincha", detail: "Anticipo 50% PED-1043 · validado", debit: 1367.35, credit: 0 },
    { id: "j15", date: daysAgoIso(5, 9), doc: "REC-0402", account: "2050 Anticipos clientes", detail: "Anticipo Estudio Barragán", debit: 0, credit: 1367.35 },
  ],
  invoices: [
    { id: "i1", number: "001-001-000000231", auth: "2109202501179234567800112345678914509876543210987", customerId: "c6", customer: "Hotel Plaza Grande Suites", date: daysAgoIso(0, 9), base: 4428, iva: 664.2, total: 5092.2, status: "pagada", orderId: "o5" },
    { id: "i2", number: "001-001-000000230", auth: "1809202501179234567800112345678914509876543211245", customerId: "c2", customer: "Corporación Quiport Offices", date: daysAgoIso(2, 16), base: 4250, iva: 637.5, total: 4887.5, status: "por_cobrar", orderId: "o2" },
    { id: "i3", number: "001-001-000000229", auth: "1209202501179234567800112345678914509876543219832", customerId: "c3", customer: "Distribuidora Mueblisur", date: daysAgoIso(8, 14), base: 2407, iva: 361.05, total: 2768.05, status: "emitida", orderId: "o6" },
    { id: "i4", number: "001-001-000000228", auth: "2908202501179234567800112345678914509876543210771", customerId: "c2", customer: "Corporación Quiport Offices", date: daysAgoIso(25, 10), base: 2208, iva: 331.2, total: 2539.2, status: "pagada", orderId: "o7" },
    { id: "i5", number: "001-001-000000227", auth: "2508202501179234567800112345678914509876543215540", customerId: "c1", customer: "María Fernanda Icaza", date: daysAgoIso(30, 12), base: 1189, iva: 178.35, total: 1367.35, status: "pagada", orderId: null },
    { id: "i6", number: "001-001-000000226", auth: "2008202501179234567800112345678914509876543216612", customerId: "c4", customer: "Estudio Arq. Barragán", date: daysAgoIso(38, 11), base: 3900, iva: 585, total: 4485, status: "pagada", orderId: null },
  ],
  notas: [
    { id: "nc1", number: "001-001-000000012", auth: "1508202501179234567800112345678914509876543214409", invoiceNumber: "001-001-000000224", customer: "Distribuidora Mueblisur", date: daysAgoIso(42, 10), motivo: "Devolución por daño en transporte (1 sofá)", amount: 953.35 },
  ],
  despachos: [
    {
      id: "d1", code: "DSP-3019", orderId: "o5", orderCode: "PED-1038", customer: "Hotel Plaza Grande Suites", city: "Quito",
      transportId: "s6", placa: "GSF-2210", conductor: "M. Saltos", motivo: "venta", fecha: daysAgoIso(3, 8),
      ruta: "Bodega Central (Calderón) → Centro Histórico, Quito", bultos: 12, pesoKg: 312,
      guia: { numero: "001-001-000000056", auth: "0209202501179234567800112345678914509876543217788", xml: "<guiaRemision>\n  <infoTributaria><ruc>1792345678001</ruc><razonSocial>Andina Madera & Hogar S.A.</razonSocial></infoTributaria>\n  <infoGuia><motivo>Venta</motivo><dirPartida>Panamericana Norte km 14, Calderón</dirPartida></infoGuia>\n  <transportista><razonSocial>Fletes Rápidos GYE</razonSocial><placa>GSF-2210</placa></transportista>\n  <ruta>Calderón → Centro Histórico, Quito</ruta>\n  <bultos>12</bultos><pesoKg>312</pesoKg>\n</guiaRemision>" },
      estado: "entregado",
    },
    {
      id: "d2", code: "DSP-3021", orderId: "o1", orderCode: "PED-1041", customer: "María Fernanda Icaza", city: "Quito",
      transportId: "s5", placa: "PCH-1194", conductor: "J. Tipán", motivo: "venta", fecha: daysAgoIso(1, 9),
      ruta: "Showroom Eloy Alfaro → Cumbayá, Quito", bultos: 2, pesoKg: 68,
      guia: null,
      estado: "en_ruta",
    },
  ],
  materials: [
    { id: "mt1", code: "MP-001", name: "Tabla laurel 2\"", unit: "und", stock: 64, min: 30, costUnit: 14.5, supplierId: "s1" },
    { id: "mt2", code: "MP-002", name: "Tabla roble 2\"", unit: "und", stock: 38, min: 25, costUnit: 22.8, supplierId: "s1" },
    { id: "mt3", code: "MP-003", name: "Triplex 18mm", unit: "plan", stock: 14, min: 10, costUnit: 47, supplierId: "s1" },
    { id: "mt4", code: "MP-004", name: "Espuma D30", unit: "plan", stock: 26, min: 15, costUnit: 7, supplierId: "s2" },
    { id: "mt5", code: "MP-005", name: "Lino crudo T-04", unit: "m", stock: 41, min: 30, costUnit: 9.5, supplierId: "s3" },
    { id: "mt6", code: "MP-006", name: "Bouclé esmeralda", unit: "m", stock: 12, min: 20, costUnit: 11, supplierId: "s3" },
    { id: "mt7", code: "MP-007", name: "Base giratoria metal", unit: "und", stock: 3, min: 12, costUnit: 22, supplierId: "s4" },
    { id: "mt8", code: "MP-008", name: "Canto PVC nogal", unit: "m", stock: 140, min: 60, costUnit: 0.8, supplierId: "s1" },
  ],
  boms: [
    { productId: "p1", lines: [{ materialId: "mt1", qty: 9, unit: "und" }, { materialId: "mt4", qty: 8, unit: "plan" }, { materialId: "mt5", qty: 11, unit: "m" }], laborMin: 960 },
    { productId: "p2", lines: [{ materialId: "mt2", qty: 14, unit: "und" }, { materialId: "mt5", qty: 4.5, unit: "m" }, { materialId: "mt4", qty: 6, unit: "plan" }], laborMin: 1200 },
    { productId: "p4", lines: [{ materialId: "mt3", qty: 6, unit: "plan" }, { materialId: "mt8", qty: 30, unit: "m" }, { materialId: "mt1", qty: 4, unit: "und" }], laborMin: 840 },
    { productId: "p6", lines: [{ materialId: "mt6", qty: 4, unit: "m" }, { materialId: "mt7", qty: 1, unit: "und" }, { materialId: "mt4", qty: 2, unit: "plan" }], laborMin: 300 },
  ],
  events: [
    { id: "e1", ts: Date.now() - 42000, type: "pago", msg: "Recibo REC-0407 registrado · esperando validación del dueño" },
    { id: "e2", ts: Date.now() - 96000, type: "stock", msg: "Ingreso bodega +4 · DOR-030 Cama King Roble" },
    { id: "e3", ts: Date.now() - 180000, type: "web", msg: "Pedido bajo specs recibido del cotizador web · PED-1045" },
    { id: "e4", ts: Date.now() - 300000, type: "taller", msg: "OF-2101 pasó a ENSAMBLAJE · Diego Guamán" },
    { id: "e5", ts: Date.now() - 420000, type: "factura", msg: "FAC-000231 autorizada por SRI · Hotel Plaza Grande" },
  ],
  team: [
    { id: "t1", name: "Andrés Yépez", role: "gerencia", email: "gerencia@andinahogar.ec", online: true, lastActive: "ahora" },
    { id: "t2", name: "Paola Cevallos", role: "vendedor", email: "ventas@andinahogar.ec", online: true, lastActive: "hace 2min" },
    { id: "t3", name: "Luis Chaluis", role: "bodega", email: "bodega@andinahogar.ec", online: true, lastActive: "hace 5min" },
    { id: "t4", name: "Rocío Mena", role: "contabilidad", email: "contabilidad@andinahogar.ec", online: false, lastActive: "hace 1h" },
    { id: "t5", name: "Diego Guamán", role: "taller", email: "taller@andinahogar.ec", online: true, lastActive: "hace 12min" },
  ],
  settings: {
    company: { name: "Andina Madera & Hogar S.A.", ruc: "1792345678001", address: "Av. Eloy Alfaro N34-211 y Rusia, Quito", phone: "02 245 8890", email: "hola@andinahogar.ec" },
    payphone: { mode: "sandbox", shopId: "SHP-EC-0042", terminalId: "TRM-01", token: "sbx_7f3Kp92MzQ81xVc4" },
    linkBase: "https://pagos.andinahogar.ec/lnk",
    sequence: { invoice: 232, order: 1046, link: 128, recibo: 408, despacho: 3022, guia: 57, nc: 13 },
  },
  session: { events: 5, salesToday: 5092.2, peakEps: 0, startedAt: Date.now() },
});
